from enum import Enum

# Resource enums
class Resource(Enum):
    """Resources for the API."""
    HEALTH = "health"
    CONSTITUENCY = "constituency"
    ELECTION = "election"
    VOTER = "voter"
    ADDRESS = "address"
    BALLOT_TOKEN = "ballot_token"
    VOTE = "vote"
    SEAT_ALLOCATION = "seat_allocation"
    TALLY_RESULT = "tally_result"
    VOTER_PASSPORT = "voter_passport"
    VOTER_LEDGER = "voter_ledger"
    OFFICIAL = "official"
    CANDIDATE = "candidate"
    PARTY = "party"
    REFERENDUM = "referendum"
    BIOMETRIC = "biometric"
    ERROR_REPORT = "error_report"
    INVESTIGATION = "investigation"
    AUDIT_LOG = "audit_log"
    AUTH = "auth"
    RESULT = "result"
