"""add voter passport table and immigration status fields

Revision ID: c84653e7a320
Revises: 9a956bf3076b
Create Date: 2026-03-20 22:46:21.784748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c84653e7a320'
down_revision: Union[str, None] = '9a956bf3076b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voter_passport',
    sa.Column('voter_id', sa.UUID(), nullable=False),
    sa.Column('passport_number', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('passport_number_search_token', sa.String(length=64), nullable=True),
    sa.Column('issuing_country', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('expiry_date', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text("timezone('utc', now())"), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text("timezone('utc', now())"), nullable=False),
    sa.ForeignKeyConstraint(['voter_id'], ['public.voter.id'], name=op.f('fk_voter_passport_voter_id_voter'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_voter_passport')),
    sa.UniqueConstraint('passport_number_search_token', name='uq_voter_passport_passport_number_search_token'),
    schema='public'
    )
    op.create_index(op.f('ix_public_voter_passport_passport_number_search_token'), 'voter_passport', ['passport_number_search_token'], unique=True, schema='public')
    op.create_index(op.f('ix_public_voter_passport_voter_id'), 'voter_passport', ['voter_id'], unique=False, schema='public')
    op.drop_index(op.f('ix_address_address_status'), table_name='address')
    op.drop_index(op.f('ix_address_postcode_search_token'), table_name='address')
    op.create_index(op.f('ix_public_address_address_status'), 'address', ['address_status'], unique=False, schema='public')
    op.create_index(op.f('ix_public_address_postcode_search_token'), 'address', ['postcode_search_token'], unique=False, schema='public')
    op.drop_constraint(op.f('fk_address_voter_id_voter'), 'address', type_='foreignkey')
    op.create_foreign_key(op.f('fk_address_voter_id_voter'), 'address', 'voter', ['voter_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('fk_ballot_token_election_id_election'), 'ballot_token', type_='foreignkey')
    op.drop_constraint(op.f('fk_ballot_token_constituency_id_constituency'), 'ballot_token', type_='foreignkey')
    op.create_foreign_key(op.f('fk_ballot_token_election_id_election'), 'ballot_token', 'election', ['election_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_ballot_token_constituency_id_constituency'), 'ballot_token', 'constituency', ['constituency_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('fk_biometric_template_voter_id_voter'), 'biometric_template', type_='foreignkey')
    op.create_foreign_key(op.f('fk_biometric_template_voter_id_voter'), 'biometric_template', 'voter', ['voter_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('fk_candidate_constituency_id_constituency'), 'candidate', type_='foreignkey')
    op.drop_constraint(op.f('fk_candidate_election_id_election'), 'candidate', type_='foreignkey')
    op.create_foreign_key(op.f('fk_candidate_election_id_election'), 'candidate', 'election', ['election_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_candidate_constituency_id_constituency'), 'candidate', 'constituency', ['constituency_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('fk_election_created_by_election_official'), 'election', type_='foreignkey')
    op.create_foreign_key(op.f('fk_election_created_by_election_official'), 'election', 'election_official', ['created_by'], ['id'], source_schema='public', referent_schema='public', ondelete='SET NULL')
    op.drop_constraint(op.f('fk_election_official_constituency_id_constituency'), 'election_official', type_='foreignkey')
    op.drop_constraint(op.f('fk_election_official_created_by_election_official'), 'election_official', type_='foreignkey')
    op.create_foreign_key(op.f('fk_election_official_created_by_election_official'), 'election_official', 'election_official', ['created_by'], ['id'], source_schema='public', referent_schema='public', ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_election_official_constituency_id_constituency'), 'election_official', 'constituency', ['constituency_id'], ['id'], source_schema='public', referent_schema='public', ondelete='SET NULL')
    op.drop_index(op.f('ix_encryption_key_org_id'), table_name='encryption_key')
    op.create_index(op.f('ix_public_encryption_key_org_id'), 'encryption_key', ['org_id'], unique=False, schema='public')
    op.drop_constraint(op.f('fk_error_report_election_id_election'), 'error_report', type_='foreignkey')
    op.drop_constraint(op.f('fk_error_report_reported_by_election_official'), 'error_report', type_='foreignkey')
    op.create_foreign_key(op.f('fk_error_report_election_id_election'), 'error_report', 'election', ['election_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_error_report_reported_by_election_official'), 'error_report', 'election_official', ['reported_by'], ['id'], source_schema='public', referent_schema='public', ondelete='SET NULL')
    op.drop_constraint(op.f('fk_investigation_election_id_election'), 'investigation', type_='foreignkey')
    op.drop_constraint(op.f('fk_investigation_assigned_to_election_official'), 'investigation', type_='foreignkey')
    op.drop_constraint(op.f('fk_investigation_error_id_error_report'), 'investigation', type_='foreignkey')
    op.drop_constraint(op.f('fk_investigation_raised_by_election_official'), 'investigation', type_='foreignkey')
    op.drop_constraint(op.f('fk_investigation_resolved_by_election_official'), 'investigation', type_='foreignkey')
    op.create_foreign_key(op.f('fk_investigation_resolved_by_election_official'), 'investigation', 'election_official', ['resolved_by'], ['id'], source_schema='public', referent_schema='public', ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_investigation_raised_by_election_official'), 'investigation', 'election_official', ['raised_by'], ['id'], source_schema='public', referent_schema='public', ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_investigation_error_id_error_report'), 'investigation', 'error_report', ['error_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_investigation_election_id_election'), 'investigation', 'election', ['election_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_investigation_assigned_to_election_official'), 'investigation', 'election_official', ['assigned_to'], ['id'], source_schema='public', referent_schema='public', ondelete='SET NULL')
    op.drop_constraint(op.f('fk_seat_allocation_constituency_id_constituency'), 'seat_allocation', type_='foreignkey')
    op.drop_constraint(op.f('fk_seat_allocation_verified_by_election_official'), 'seat_allocation', type_='foreignkey')
    op.drop_constraint(op.f('fk_seat_allocation_election_id_election'), 'seat_allocation', type_='foreignkey')
    op.create_foreign_key(op.f('fk_seat_allocation_constituency_id_constituency'), 'seat_allocation', 'constituency', ['constituency_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_seat_allocation_election_id_election'), 'seat_allocation', 'election', ['election_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_seat_allocation_verified_by_election_official'), 'seat_allocation', 'election_official', ['verified_by'], ['id'], source_schema='public', referent_schema='public', ondelete='SET NULL')
    op.drop_constraint(op.f('fk_tally_result_constituency_id_constituency'), 'tally_result', type_='foreignkey')
    op.drop_constraint(op.f('fk_tally_result_election_id_election'), 'tally_result', type_='foreignkey')
    op.drop_constraint(op.f('fk_tally_result_candidate_id_candidate'), 'tally_result', type_='foreignkey')
    op.create_foreign_key(op.f('fk_tally_result_candidate_id_candidate'), 'tally_result', 'candidate', ['candidate_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_tally_result_election_id_election'), 'tally_result', 'election', ['election_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_tally_result_constituency_id_constituency'), 'tally_result', 'constituency', ['constituency_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('fk_vote_candidate_id_candidate'), 'vote', type_='foreignkey')
    op.drop_constraint(op.f('fk_vote_election_id_election'), 'vote', type_='foreignkey')
    op.drop_constraint(op.f('fk_vote_constituency_id_constituency'), 'vote', type_='foreignkey')
    op.create_foreign_key(op.f('fk_vote_candidate_id_candidate'), 'vote', 'candidate', ['candidate_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_vote_constituency_id_constituency'), 'vote', 'constituency', ['constituency_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_vote_election_id_election'), 'vote', 'election', ['election_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.add_column('voter', sa.Column('nationality_category', sa.String(length=50), nullable=True))
    # Backfill existing rows, then make NOT NULL
    op.execute("UPDATE public.voter SET nationality_category = 'BRITISH_CITIZEN' WHERE nationality_category IS NULL")
    op.alter_column('voter', 'nationality_category', nullable=False, schema='public')
    op.add_column('voter', sa.Column('immigration_status', sa.String(length=50), nullable=True))
    op.add_column('voter', sa.Column('immigration_status_expiry', sa.TIMESTAMP(timezone=True), nullable=True))
    op.drop_index(op.f('ix_public_voter_national_insurance_number'), table_name='voter')
    op.drop_index(op.f('ix_public_voter_voter_reference'), table_name='voter')
    op.drop_index(op.f('ix_voter_email_search_token'), table_name='voter')
    op.drop_index(op.f('ix_voter_national_insurance_number_search_token'), table_name='voter')
    op.drop_index(op.f('ix_voter_passport_number_search_token'), table_name='voter')
    op.drop_index(op.f('ix_voter_voter_reference_search_token'), table_name='voter')
    op.drop_index(op.f('ix_voter_voter_status'), table_name='voter')
    op.create_index(op.f('ix_public_voter_email_search_token'), 'voter', ['email_search_token'], unique=False, schema='public')
    op.create_index(op.f('ix_public_voter_national_insurance_number_search_token'), 'voter', ['national_insurance_number_search_token'], unique=True, schema='public')
    op.create_index(op.f('ix_public_voter_nationality_category'), 'voter', ['nationality_category'], unique=False, schema='public')
    op.create_index(op.f('ix_public_voter_voter_reference_search_token'), 'voter', ['voter_reference_search_token'], unique=True, schema='public')
    op.create_index(op.f('ix_public_voter_voter_status'), 'voter', ['voter_status'], unique=False, schema='public')
    op.create_unique_constraint('uq_voter_national_insurance_number_search_token', 'voter', ['national_insurance_number_search_token'], schema='public')
    op.create_unique_constraint('uq_voter_voter_reference_search_token', 'voter', ['voter_reference_search_token'], schema='public')
    op.drop_constraint(op.f('fk_voter_constituency_id_constituency'), 'voter', type_='foreignkey')
    op.create_foreign_key(op.f('fk_voter_constituency_id_constituency'), 'voter', 'constituency', ['constituency_id'], ['id'], source_schema='public', referent_schema='public', ondelete='SET NULL')
    op.drop_column('voter', 'passport_expiry_date')
    op.drop_column('voter', 'maiden_name')
    op.drop_column('voter', 'passport_country')
    op.drop_column('voter', 'passport_number_search_token')
    op.drop_column('voter', 'passport_number')
    op.drop_constraint(op.f('fk_voter_ledger_voter_id_voter'), 'voter_ledger', type_='foreignkey')
    op.drop_constraint(op.f('fk_voter_ledger_election_id_election'), 'voter_ledger', type_='foreignkey')
    op.create_foreign_key(op.f('fk_voter_ledger_voter_id_voter'), 'voter_ledger', 'voter', ['voter_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_voter_ledger_election_id_election'), 'voter_ledger', 'election', ['election_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_voter_ledger_election_id_election'), 'voter_ledger', schema='public', type_='foreignkey')
    op.drop_constraint(op.f('fk_voter_ledger_voter_id_voter'), 'voter_ledger', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('fk_voter_ledger_election_id_election'), 'voter_ledger', 'election', ['election_id'], ['id'])
    op.create_foreign_key(op.f('fk_voter_ledger_voter_id_voter'), 'voter_ledger', 'voter', ['voter_id'], ['id'])
    op.add_column('voter', sa.Column('passport_number', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('voter', sa.Column('passport_number_search_token', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('voter', sa.Column('passport_country', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('voter', sa.Column('maiden_name', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.add_column('voter', sa.Column('passport_expiry_date', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_voter_constituency_id_constituency'), 'voter', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('fk_voter_constituency_id_constituency'), 'voter', 'constituency', ['constituency_id'], ['id'])
    op.drop_constraint('uq_voter_voter_reference_search_token', 'voter', schema='public', type_='unique')
    op.drop_constraint('uq_voter_national_insurance_number_search_token', 'voter', schema='public', type_='unique')
    op.drop_index(op.f('ix_public_voter_voter_status'), table_name='voter', schema='public')
    op.drop_index(op.f('ix_public_voter_voter_reference_search_token'), table_name='voter', schema='public')
    op.drop_index(op.f('ix_public_voter_nationality_category'), table_name='voter', schema='public')
    op.drop_index(op.f('ix_public_voter_national_insurance_number_search_token'), table_name='voter', schema='public')
    op.drop_index(op.f('ix_public_voter_email_search_token'), table_name='voter', schema='public')
    op.create_index(op.f('ix_voter_voter_status'), 'voter', ['voter_status'], unique=False)
    op.create_index(op.f('ix_voter_voter_reference_search_token'), 'voter', ['voter_reference_search_token'], unique=True)
    op.create_index(op.f('ix_voter_passport_number_search_token'), 'voter', ['passport_number_search_token'], unique=True)
    op.create_index(op.f('ix_voter_national_insurance_number_search_token'), 'voter', ['national_insurance_number_search_token'], unique=True)
    op.create_index(op.f('ix_voter_email_search_token'), 'voter', ['email_search_token'], unique=False)
    op.create_index(op.f('ix_public_voter_voter_reference'), 'voter', ['voter_reference'], unique=False)
    op.create_index(op.f('ix_public_voter_national_insurance_number'), 'voter', ['national_insurance_number'], unique=True)
    op.drop_column('voter', 'immigration_status_expiry')
    op.drop_column('voter', 'immigration_status')
    op.drop_column('voter', 'nationality_category')
    op.drop_constraint(op.f('fk_vote_election_id_election'), 'vote', schema='public', type_='foreignkey')
    op.drop_constraint(op.f('fk_vote_constituency_id_constituency'), 'vote', schema='public', type_='foreignkey')
    op.drop_constraint(op.f('fk_vote_candidate_id_candidate'), 'vote', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('fk_vote_constituency_id_constituency'), 'vote', 'constituency', ['constituency_id'], ['id'])
    op.create_foreign_key(op.f('fk_vote_election_id_election'), 'vote', 'election', ['election_id'], ['id'])
    op.create_foreign_key(op.f('fk_vote_candidate_id_candidate'), 'vote', 'candidate', ['candidate_id'], ['id'])
    op.drop_constraint(op.f('fk_tally_result_constituency_id_constituency'), 'tally_result', schema='public', type_='foreignkey')
    op.drop_constraint(op.f('fk_tally_result_election_id_election'), 'tally_result', schema='public', type_='foreignkey')
    op.drop_constraint(op.f('fk_tally_result_candidate_id_candidate'), 'tally_result', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('fk_tally_result_candidate_id_candidate'), 'tally_result', 'candidate', ['candidate_id'], ['id'])
    op.create_foreign_key(op.f('fk_tally_result_election_id_election'), 'tally_result', 'election', ['election_id'], ['id'])
    op.create_foreign_key(op.f('fk_tally_result_constituency_id_constituency'), 'tally_result', 'constituency', ['constituency_id'], ['id'])
    op.drop_constraint(op.f('fk_seat_allocation_verified_by_election_official'), 'seat_allocation', schema='public', type_='foreignkey')
    op.drop_constraint(op.f('fk_seat_allocation_election_id_election'), 'seat_allocation', schema='public', type_='foreignkey')
    op.drop_constraint(op.f('fk_seat_allocation_constituency_id_constituency'), 'seat_allocation', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('fk_seat_allocation_election_id_election'), 'seat_allocation', 'election', ['election_id'], ['id'])
    op.create_foreign_key(op.f('fk_seat_allocation_verified_by_election_official'), 'seat_allocation', 'election_official', ['verified_by'], ['id'])
    op.create_foreign_key(op.f('fk_seat_allocation_constituency_id_constituency'), 'seat_allocation', 'constituency', ['constituency_id'], ['id'])
    op.drop_constraint(op.f('fk_investigation_assigned_to_election_official'), 'investigation', schema='public', type_='foreignkey')
    op.drop_constraint(op.f('fk_investigation_election_id_election'), 'investigation', schema='public', type_='foreignkey')
    op.drop_constraint(op.f('fk_investigation_error_id_error_report'), 'investigation', schema='public', type_='foreignkey')
    op.drop_constraint(op.f('fk_investigation_raised_by_election_official'), 'investigation', schema='public', type_='foreignkey')
    op.drop_constraint(op.f('fk_investigation_resolved_by_election_official'), 'investigation', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('fk_investigation_resolved_by_election_official'), 'investigation', 'election_official', ['resolved_by'], ['id'])
    op.create_foreign_key(op.f('fk_investigation_raised_by_election_official'), 'investigation', 'election_official', ['raised_by'], ['id'])
    op.create_foreign_key(op.f('fk_investigation_error_id_error_report'), 'investigation', 'error_report', ['error_id'], ['id'])
    op.create_foreign_key(op.f('fk_investigation_assigned_to_election_official'), 'investigation', 'election_official', ['assigned_to'], ['id'])
    op.create_foreign_key(op.f('fk_investigation_election_id_election'), 'investigation', 'election', ['election_id'], ['id'])
    op.drop_constraint(op.f('fk_error_report_reported_by_election_official'), 'error_report', schema='public', type_='foreignkey')
    op.drop_constraint(op.f('fk_error_report_election_id_election'), 'error_report', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('fk_error_report_reported_by_election_official'), 'error_report', 'election_official', ['reported_by'], ['id'])
    op.create_foreign_key(op.f('fk_error_report_election_id_election'), 'error_report', 'election', ['election_id'], ['id'])
    op.drop_index(op.f('ix_public_encryption_key_org_id'), table_name='encryption_key', schema='public')
    op.create_index(op.f('ix_encryption_key_org_id'), 'encryption_key', ['org_id'], unique=False)
    op.drop_constraint(op.f('fk_election_official_constituency_id_constituency'), 'election_official', schema='public', type_='foreignkey')
    op.drop_constraint(op.f('fk_election_official_created_by_election_official'), 'election_official', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('fk_election_official_created_by_election_official'), 'election_official', 'election_official', ['created_by'], ['id'])
    op.create_foreign_key(op.f('fk_election_official_constituency_id_constituency'), 'election_official', 'constituency', ['constituency_id'], ['id'])
    op.drop_constraint(op.f('fk_election_created_by_election_official'), 'election', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('fk_election_created_by_election_official'), 'election', 'election_official', ['created_by'], ['id'])
    op.drop_constraint(op.f('fk_candidate_constituency_id_constituency'), 'candidate', schema='public', type_='foreignkey')
    op.drop_constraint(op.f('fk_candidate_election_id_election'), 'candidate', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('fk_candidate_election_id_election'), 'candidate', 'election', ['election_id'], ['id'])
    op.create_foreign_key(op.f('fk_candidate_constituency_id_constituency'), 'candidate', 'constituency', ['constituency_id'], ['id'])
    op.drop_constraint(op.f('fk_biometric_template_voter_id_voter'), 'biometric_template', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('fk_biometric_template_voter_id_voter'), 'biometric_template', 'voter', ['voter_id'], ['id'])
    op.drop_constraint(op.f('fk_ballot_token_constituency_id_constituency'), 'ballot_token', schema='public', type_='foreignkey')
    op.drop_constraint(op.f('fk_ballot_token_election_id_election'), 'ballot_token', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('fk_ballot_token_constituency_id_constituency'), 'ballot_token', 'constituency', ['constituency_id'], ['id'])
    op.create_foreign_key(op.f('fk_ballot_token_election_id_election'), 'ballot_token', 'election', ['election_id'], ['id'])
    op.drop_constraint(op.f('fk_address_voter_id_voter'), 'address', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('fk_address_voter_id_voter'), 'address', 'voter', ['voter_id'], ['id'])
    op.drop_index(op.f('ix_public_address_postcode_search_token'), table_name='address', schema='public')
    op.drop_index(op.f('ix_public_address_address_status'), table_name='address', schema='public')
    op.create_index(op.f('ix_address_postcode_search_token'), 'address', ['postcode_search_token'], unique=False)
    op.create_index(op.f('ix_address_address_status'), 'address', ['address_status'], unique=False)
    op.drop_index(op.f('ix_public_voter_passport_voter_id'), table_name='voter_passport', schema='public')
    op.drop_index(op.f('ix_public_voter_passport_passport_number_search_token'), table_name='voter_passport', schema='public')
    op.drop_table('voter_passport', schema='public')
    # ### end Alembic commands ###
