import hmac
import hashlib
import os
import struct

import boto3
import structlog
from cryptography.hazmat.primitives.ciphers.aead import AESGCM

from .base import BaseEncryption, EncryptedField

logger = structlog.get_logger()


class AWSKMSEncryption(BaseEncryption):
    """AWS KMS-based field encryption using envelope encryption.

    Each value is encrypted with a unique AES-256-GCM data key generated by KMS.
    The encrypted data key is stored alongside the ciphertext so KMS is only
    needed at encrypt/decrypt time, not for key storage.

    Wire format: [4-byte key_len][encrypted_data_key][12-byte nonce][ciphertext]
    """

    def __init__(self, key_id: str, region: str, hmac_secret: str):
        self._key_id = key_id
        self._hmac_secret = hmac_secret.encode() if isinstance(hmac_secret, str) else hmac_secret
        self._kms = boto3.client("kms", region_name=region)
        logger.info("AWSKMSEncryption initialised", key_id=key_id, region=region)

    def encrypt(self, plaintext: str) -> EncryptedField:
        response = self._kms.generate_data_key(KeyId=self._key_id, KeySpec="AES_256")
        plaintext_key: bytes = response["Plaintext"]   # 32 bytes, never stored
        encrypted_key: bytes = response["CiphertextBlob"]

        try:
            nonce = os.urandom(12)
            aesgcm = AESGCM(plaintext_key)
            ciphertext = aesgcm.encrypt(nonce, plaintext.encode(), None)
        finally:
            del plaintext_key

        # Pack: 4-byte big-endian key length | encrypted key | 12-byte nonce | ciphertext
        packed = struct.pack(">I", len(encrypted_key)) + encrypted_key + nonce + ciphertext

        return EncryptedField(
            ciphertext=packed,
            search_token=self.generate_search_token(plaintext),
        )

    def decrypt(self, encrypted: EncryptedField) -> str:
        data = encrypted.ciphertext
        (key_len,) = struct.unpack(">I", data[:4])
        encrypted_key = data[4 : 4 + key_len]
        nonce = data[4 + key_len : 4 + key_len + 12]
        ciphertext = data[4 + key_len + 12 :]

        response = self._kms.decrypt(CiphertextBlob=encrypted_key)
        plaintext_key: bytes = response["Plaintext"]

        try:
            aesgcm = AESGCM(plaintext_key)
            plaintext = aesgcm.decrypt(nonce, ciphertext, None)
        finally:
            del plaintext_key

        return plaintext.decode()

    def generate_search_token(self, value: str) -> bytes:
        return hmac.new(self._hmac_secret, value.lower().encode(), hashlib.sha256).digest()
