const UK_COUNTIES = [
    "Aberdeenshire",
    "Angus",
    "Antrim",
    "Argyll and Bute",
    "Armagh",
    "Ayrshire",
    "Banffshire",
    "Bedfordshire",
    "Berkshire",
    "Berwickshire",
    "Blaenau Gwent",
    "Bridgend",
    "Bristol",
    "Buckinghamshire",
    "Caerphilly",
    "Caithness",
    "Cambridgeshire",
    "Cardiff",
    "Carmarthenshire",
    "Ceredigion",
    "Cheshire",
    "City of Edinburgh",
    "City of London",
    "Clackmannanshire",
    "Conwy",
    "Cornwall",
    "County Durham",
    "Cumbria",
    "Denbighshire",
    "Derbyshire",
    "Devon",
    "Dorset",
    "Down",
    "Dumfries and Galloway",
    "Dunbartonshire",
    "Dundee",
    "East Lothian",
    "East Riding of Yorkshire",
    "Essex",
    "Falkirk",
    "Fermanagh",
    "Fife",
    "Flintshire",
    "Glasgow",
    "Gloucestershire",
    "Greater London",
    "Greater Manchester",
    "Gwynedd",
    "Hampshire",
    "Herefordshire",
    "Hertfordshire",
    "Highland",
    "Inverclyde",
    "Isle of Anglesey",
    "Isle of Wight",
    "Kent",
    "Kincardineshire",
    "Lancashire",
    "Leicestershire",
    "Lincolnshire",
    "Londonderry",
    "Merseyside",
    "Merthyr Tydfil",
    "Midlothian",
    "Monmouthshire",
    "Moray",
    "Neath Port Talbot",
    "Newport",
    "Norfolk",
    "North Ayrshire",
    "North Lanarkshire",
    "North Yorkshire",
    "Northamptonshire",
    "Northumberland",
    "Nottinghamshire",
    "Orkney Islands",
    "Oxfordshire",
    "Pembrokeshire",
    "Perth and Kinross",
    "Powys",
    "Renfrewshire",
    "Rhondda Cynon Taf",
    "Rutland",
    "Scottish Borders",
    "Shetland Islands",
    "Shropshire",
    "Somerset",
    "South Ayrshire",
    "South Lanarkshire",
    "South Yorkshire",
    "Staffordshire",
    "Stirling",
    "Suffolk",
    "Surrey",
    "Swansea",
    "Torfaen",
    "Tyne and Wear",
    "Tyrone",
    "Vale of Glamorgan",
    "Warwickshire",
    "West Dunbartonshire",
    "West Lothian",
    "West Midlands",
    "West Sussex",
    "West Yorkshire",
    "Wiltshire",
    "Worcestershire",
    "Wrexham",
] as const;

export default UK_COUNTIES;
